In [ ]:
NUMPY 


In [ ]:
It is basically Numericaln Python

In [3]:
pip install numpy


Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np
a=np.array([1,2,3])

In [5]:
a


array([1, 2, 3])

In [6]:
print(type(a))

<class 'numpy.ndarray'>


In [21]:
b=np.array([[12,33,33],[2,1,3]])


In [23]:
print(type(b))

<class 'list'>


In [35]:
b.shape

(2, 3)

In [40]:
R, C= Rows & Columns 
Rows=2
Columns=3

NameError: name 'Rows' is not defined

In [10]:
c=np.array([1,2,3])
d=np.array([2,4,5])

In [11]:
+,-,*,/,//,%,**

SyntaxError: invalid syntax (3054210374.py, line 1)

In [12]:
c+d

array([3, 6, 8])

In [13]:
c-d

array([-1, -2, -2])

In [14]:
c*d


array([ 2,  8, 15])

In [15]:
c/d

array([0.5, 0.5, 0.6])

In [16]:
c//d

array([0, 0, 0])

In [17]:
c%d


array([1, 2, 3])

In [18]:
c**d


array([  1,  16, 243])

In [20]:
a=10
b=10
a is b

True

In [22]:
a=[1,2,3]
b=[2,3,1]
a is b

False

In [27]:
a=np.array([[1,2,3],[2,3,4]])
b=np.array([[2,3,4],[3,4,6]])

In [28]:
a+b


array([[ 3,  5,  7],
       [ 5,  7, 10]])

In [29]:
a-b

array([[-1, -1, -1],
       [-1, -1, -2]])

In [30]:
a*b

array([[ 2,  6, 12],
       [ 6, 12, 24]])

In [31]:
a/d

array([[0.5 , 0.5 , 0.6 ],
       [1.  , 0.75, 0.8 ]])

In [32]:
a**d

array([[   1,   16,  243],
       [   4,   81, 1024]])

In [33]:
a%d

array([[1, 2, 3],
       [0, 3, 4]])

In [34]:
a//d

array([[0, 0, 0],
       [1, 0, 0]])

In [43]:
a=np.array([[1,2,3],[2,3,4]])
b=np.array([[2,3,4],[3,4,6]])
np.dot(a,b.T)

array([[20, 29],
       [29, 42]])

In [44]:
np.transpose(b)

array([[2, 3],
       [3, 4],
       [4, 6]])

In [46]:
np.dot(a,b.T)


array([[20, 29],
       [29, 42]])

In [47]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr.shape)
print(arr.size)
print(arr.ndim)
print(arr.dtype)

(2, 3)
6
2
int64


In [48]:
print(np.sum(arr))
print(np.min(arr))
print(np.max(arr))
print(np.sum(arr,axis=0))
print(np.sum(arr,axis=1))

21
1
6
[5 7 9]
[ 6 15]
