# Q-Learning (From Basics to Backend Calculations)

# Reinforcement Learning

Reinforcement Learning (RL) is a type of Machine Learning in which an **Agent** learns by interacting with an **Environment**.

Instead of learning from labeled data, the agent learns through **Trial and Error**.

The goal is to maximize the **Total Reward**.

---

# Real Life Example

Imagine a Robot trying to reach the treasure.

```
S ----> ----> ---->
↑                 ↓
↑                 ↓
<---- <---- Goal
```

Every movement gives some reward.

```
Normal Move = -1

Wall = -10

Goal = +100
```

Initially the robot knows nothing.

After many attempts, it learns the shortest path.

---

# Basic Terminologies

## 1. Agent

The learner.

Example

```
Robot

Self Driving Car

Game Player
```

---

## 2. Environment

Everything around the agent.

Example

```
Maze

Road

Game

Grid World
```

---

## 3. State (S)

Current position of the agent.

Example

```
S1

S2

S3

S4
```

---

## 4. Action (A)

Possible moves.

```
Up

Down

Left

Right
```

---

## 5. Reward (R)

Feedback received after taking an action.

Example

```
Goal = +100

Wall = -100

Normal Move = -1
```

---

## 6. Policy (π)

Rule followed by the agent.

Example

```
Always Move Right

Choose Random Action

Choose Best Action
```

---

## 7. Episode

One complete journey.

Example

```
Start

↓

Move

↓

Move

↓

Goal

Episode Finished
```

---

## 8. Discount Factor (γ)

Importance of Future Rewards.

```
0 ≤ γ ≤ 1
```

Example

```
γ = 0

Only Current Reward Matters

γ = 1

Future Reward Matters Equally
```

Usually

```
γ = 0.9
```

---

## 9. Learning Rate (α)

Controls how much new learning replaces old learning.

```
0 ≤ α ≤ 1
```

Usually

```
α = 0.1

or

0.5
```

---

# Problem Statement

Robot has to move from Start to Goal.

```
+---------+---------+
|   S1    |   S2    |
+---------+---------+
|   S3    | Goal    |
+---------+---------+
```

Actions

```
Up

Down

Left

Right
```

Rewards

```
Goal = +100

Normal Move = -1
```

---

# Step 1

Create State Table

| State | Description |
|--------|-------------|
| S1 | Start |
| S2 | Top Right |
| S3 | Bottom Left |
| Goal | Destination |

---

# Step 2

Possible Actions

| State | Up | Down | Left | Right |
|--------|----|------|------|--------|
| S1 | ❌ | S3 | ❌ | S2 |
| S2 | ❌ | Goal | S1 | ❌ |
| S3 | S1 | ❌ | ❌ | Goal |
| Goal | End | End | End | End |

---

# Step 3

Initialize Q Table

Initially the robot knows nothing.

Every value becomes zero.

| State | Up | Down | Left | Right |
|--------|----|------|------|--------|
| S1 |0|0|0|0|
| S2 |0|0|0|0|
| S3 |0|0|0|0|
| Goal|0|0|0|0|

This is called the **Initial Q Table**.

---

# Why Q Table?

Q stands for

```
Quality
```

It stores

```
How good is taking Action A from State S?
```

---

# Step 4

Robot Starts Learning

Current State

```
S1
```

Possible Actions

```
Down

Right
```

Suppose robot chooses

```
Right
```

Now robot reaches

```
S2
```

Reward

```
-1
```

---

# Q-Learning Formula

The heart of the algorithm.

\[
Q(s,a)=Q(s,a)+\alpha\left[R+\gamma\max Q(s',a')-Q(s,a)\right]
\]

---

# Formula Meaning

| Symbol | Meaning |
|----------|----------|
| Q(s,a) | Current Q Value |
| α | Learning Rate |
| R | Reward |
| γ | Discount Factor |
| max Q(s',a') | Best Future Reward |

---

# Step 5

First Update

Current Q

```
0
```

Reward

```
-1
```

Future Maximum Q

```
0
```

Learning Rate

```
0.5
```

Discount Factor

```
0.9
```

Calculation

```
Qnew

=0+0.5×

(-1+0.9×0−0)

=-0.5
```

Updated Q Table

| State | Up | Down | Left | Right |
|--------|----|------|------|--------|
| S1 |0|0|0|-0.5|
| S2 |0|0|0|0|
| S3 |0|0|0|0|
| Goal|0|0|0|0|

---

# Step 6

Second Move

Robot

```
S2
```

Action

```
Down
```

Reached

```
Goal
```

Reward

```
100
```

Current Q

```
0
```

Future Q

```
0
```

Calculation

```
Qnew

=0+0.5×

(100+0.9×0−0)

=50
```

Updated Q Table

| State | Up | Down | Left | Right |
|--------|----|------|------|--------|
| S1 |0|0|0|-0.5|
| S2 |0|50|0|0|
| S3 |0|0|0|0|
| Goal|0|0|0|0|

---

# Step 7

Another Episode

Robot again starts from S1.

Current State

```
S1
```

Action

```
Right
```

Reward

```
-1
```

Future Maximum Q

```
50
```

Current Q

```
-0.5
```

Calculation

```
Qnew

=-0.5

+

0.5×

(-1+0.9×50+0.5)

=-0.5

+

22.25

=21.75
```

Updated Table

| State | Up | Down | Left | Right |
|--------|----|------|------|--------|
| S1 |0|0|0|21.75|
| S2 |0|50|0|0|
| S3 |0|0|0|0|
| Goal|0|0|0|0|

Notice how the value of taking **Right** from **S1** increased because it leads toward the Goal.

---

# After Many Episodes

The Q Table may look like this.

| State | Up | Down | Left | Right |
|--------|----|------|------|--------|
| S1 |0|10|0|85|
| S2 |0|100|40|0|
| S3 |20|0|0|90|
| Goal|0|0|0|0|

Higher Q-value means **better action**.

---

# Prediction

Suppose Robot is at

```
S1
```

Q Values

| Action | Q Value |
|----------|---------|
| Up |0|
| Down |10|
| Left |0|
| Right |85|

Prediction

```
Choose Right
```

because

```
85 is Maximum.
```

---

# Algorithm (Pseudo Code)

```
Initialize Q-table with zeros

Repeat for each Episode

    Select Current State

    Choose Action (ε-Greedy)

    Perform Action

    Observe Reward

    Observe Next State

    Update Q-value using

    Q(s,a)=Q(s,a)+α[R+γmaxQ(s',a')−Q(s,a)]

    Move to Next State

Repeat until Goal

Repeat for many Episodes
```

---

# Time Complexity

```
Training

O(Episodes × Steps)

Prediction

O(Number of Actions)
```

---

# Advantages

- Easy to implement
- Learns optimal policy
- Model-free algorithm
- No prior environment knowledge required
- Fast for small state spaces

---

# Limitations

- Q-table becomes huge for large environments
- High memory usage with many states
- Slow convergence in complex problems
- Cannot directly handle image or continuous state inputs

---

# Applications

- Robot Navigation
- Maze Solving
- Game Playing
- Traffic Signal Optimization
- Warehouse Robots
- Path Planning
- Resource Allocation
- Autonomous Systems

In [47]:
import numpy as np
import gymnasium as gym

In [49]:
env = gym.make("FrozenLake-v1", is_slippery=False)

print("States :", env.observation_space.n)
print("Actions :", env.action_space.n)

States : 16
Actions : 4


In [51]:
q_table = np.zeros((16, 4))

print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [53]:
#hyperparameters for rl
learning_rate = 0.8 #defining the right step to agent
gamma = 0.95 #how much you want your agent to explore 

epsilon = 1.0 #how much it explored 
epsilon_decay = 0.999
epsilon_min = 0.01

episodes = 20000 # 2000 times agent go from start to end 

In [55]:
for episode in range(episodes):

    state, _ = env.reset()

    done = False

    while not done:

        # Epsilon-Greedy
        if np.random.uniform(0,1) < epsilon:
            action = env.action_space.sample()
        else:
            action = np.argmax(q_table[state])

        next_state, reward, terminated, truncated, _ = env.step(action)

        done = terminated or truncated

        # Q-Learning Formula
        q_table[state, action] = q_table[state, action] + learning_rate * (
            reward + gamma * np.max(q_table[next_state]) - q_table[state, action]
        )

        state = next_state

    if epsilon > epsilon_min:
        epsilon *= epsilon_decay

In [56]:
print(q_table)

[[0.73509189 0.77378094 0.77378094 0.73509189]
 [0.73509189 0.         0.81450625 0.77378094]
 [0.77378094 0.857375   0.77378094 0.81450625]
 [0.81450625 0.         0.77378094 0.77378094]
 [0.77378094 0.81450625 0.         0.73509189]
 [0.         0.         0.         0.        ]
 [0.         0.9025     0.         0.81450625]
 [0.         0.         0.         0.        ]
 [0.81450625 0.         0.857375   0.77378094]
 [0.81450625 0.9025     0.9025     0.        ]
 [0.857375   0.95       0.         0.857375  ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.9025     0.95       0.857375  ]
 [0.9025     0.95       1.         0.9025    ]
 [0.         0.         0.         0.        ]]


In [57]:
state, _ = env.reset()

done = False

total_reward = 0

while not done:

    action = np.argmax(q_table[state])

    next_state, reward, terminated, truncated, _ = env.step(action)

    done = terminated or truncated

    total_reward += reward

    state = next_state

print("Reward :", total_reward)

Reward : 1


In [58]:
state = 0

best_action = np.argmax(q_table[state])

print("Best Action :", best_action)

Best Action : 1


# SARSA (State–Action–Reward–State–Action)

# Reinforcement Learning

SARSA is one of the most popular **On-Policy Reinforcement Learning Algorithms**.

It learns the best action by interacting with the environment and updating the Q-table based on the **actual next action chosen by the agent**.

Unlike Q-Learning, SARSA follows the same policy for both learning and action selection.

---

# Full Form of SARSA

```
S → State

A → Action

R → Reward

S → Next State

A → Next Action
```

This sequence gives the algorithm its name.

---

# Real Life Example

Imagine a delivery robot inside a warehouse.

The robot has to deliver a package to the destination safely.

```
Start ----> ---->
  |            |
  |            |
  ↓            ↓
 Safe -----> Goal
```

Rewards

```
Normal Move = -1

Obstacle = -10

Goal = +100
```

Initially the robot doesn't know the correct path.

It learns by trying different paths repeatedly.

---

# Basic Terminologies

## 1. Agent

The learner.

Example

```
Robot

Self Driving Car

Game Player
```

---

## 2. Environment

Everything around the agent.

Example

```
Maze

Road

Warehouse

Game
```

---

## 3. State (S)

Current position of the agent.

Example

```
S1

S2

S3

Goal
```

---

## 4. Action (A)

Possible moves.

```
Up

Down

Left

Right
```

---

## 5. Reward (R)

Feedback received after every action.

Example

```
Goal = +100

Obstacle = -10

Normal Move = -1
```

---

## 6. Policy (π)

Rule followed while selecting actions.

Example

```
Random

Greedy

ε-Greedy
```

SARSA learns using the same policy that it follows.

---

## 7. Episode

One complete journey.

```
Start

↓

Move

↓

Move

↓

Goal

Episode Ends
```

---

## 8. Learning Rate (α)

Controls how much new learning replaces old learning.

```
0 ≤ α ≤ 1
```

Example

```
α = 0.5
```

---

## 9. Discount Factor (γ)

Importance of future rewards.

```
0 ≤ γ ≤ 1
```

Usually

```
γ = 0.9
```

---

# Problem Statement

Robot wants to reach the Goal.

```
+---------+---------+
|   S1    |   S2    |
+---------+---------+
|   S3    | Goal    |
+---------+---------+
```

Rewards

```
Goal = +100

Normal Move = -1
```

---

# Step 1

Create State Table

| State | Description |
|--------|-------------|
| S1 | Start |
| S2 | Top Right |
| S3 | Bottom Left |
| Goal | Destination |

---

# Step 2

Possible Actions

| State | Up | Down | Left | Right |
|--------|----|------|------|--------|
| S1 | ❌ | S3 | ❌ | S2 |
| S2 | ❌ | Goal | S1 | ❌ |
| S3 | S1 | ❌ | ❌ | Goal |
| Goal | End | End | End | End |

---

# Step 3

Initialize Q Table

Initially all Q-values are zero.

| State | Up | Down | Left | Right |
|--------|----|------|------|--------|
| S1 |0|0|0|0|
| S2 |0|0|0|0|
| S3 |0|0|0|0|
| Goal|0|0|0|0|

---

# Why Q Table?

Q means

```
Quality
```

It stores

```
How good is taking Action A from State S?
```

---

# SARSA Formula

\[
Q(s,a)=Q(s,a)+\alpha\left[R+\gamma Q(s',a')-Q(s,a)\right]
\]

This is the heart of the algorithm.

---

# Formula Meaning

| Symbol | Meaning |
|----------|----------|
| Q(s,a) | Current Q Value |
| α | Learning Rate |
| R | Reward |
| γ | Discount Factor |
| Q(s',a') | Q-value of the **Actual Next Action** |

---

# Difference from Q-Learning

Q-Learning uses

```
Maximum Future Q Value
```

SARSA uses

```
Actual Next Action Q Value
```

This is why SARSA is called **On-Policy Learning**.

---

# Step 4

Current State

```
S1
```

Robot selects

```
Right
```

Moves to

```
S2
```

Reward

```
-1
```

Current Q

```
0
```

Now suppose the robot actually chooses

```
Down
```

at S2.

Current Q of

```
Q(S2,Down)
```

is

```
0
```

---

# First Update

Learning Rate

```
0.5
```

Discount Factor

```
0.9
```

Calculation

```
Qnew

=0

+

0.5×

(-1+0.9×0−0)

=-0.5
```

Updated Q Table

| State | Up | Down | Left | Right |
|--------|----|------|------|--------|
| S1 |0|0|0|-0.5|
| S2 |0|0|0|0|
| S3 |0|0|0|0|
| Goal|0|0|0|0|

---

# Step 5

Robot is now at

```
S2
```

Actual chosen action

```
Down
```

Robot reaches

```
Goal
```

Reward

```
100
```

Current Q

```
0
```

Goal has no future action.

Therefore

```
Q(Goal)=0
```

Calculation

```
Qnew

=0

+

0.5×

(100+0.9×0−0)

=50
```

Updated Table

| State | Up | Down | Left | Right |
|--------|----|------|------|--------|
| S1 |0|0|0|-0.5|
| S2 |0|50|0|0|
| S3 |0|0|0|0|
| Goal|0|0|0|0|

---

# Step 6

New Episode

Robot again starts from

```
S1
```

Chooses

```
Right
```

Reward

```
-1
```

Now suppose the robot **actually selects Left** at S2 instead of Down.

Current Q

```
Q(S2,Left)=0
```

Notice

Although

```
Q(S2,Down)=50
```

SARSA **does not use 50** because the robot actually selected **Left**.

This is the biggest difference.

Calculation

```
Qnew

=-0.5

+

0.5×

(-1+0.9×0+0.5)

=-0.75
```

Updated Table

| State | Up | Down | Left | Right |
|--------|----|------|------|--------|
| S1 |0|0|0|-0.75|
| S2 |0|50|0|0|
| S3 |0|0|0|0|
| Goal|0|0|0|0|

---

# Another Episode

Now robot chooses

```
Right
```

from S1.

At S2 it actually chooses

```
Down
```

Again.

Current Q

```
Q(S2,Down)=50
```

Calculation

```
Qnew

=-0.75

+

0.5×

(-1+0.9×50+0.75)

=-0.75

+

22.375

=21.625
```

Updated Table

| State | Up | Down | Left | Right |
|--------|----|------|------|--------|
| S1 |0|0|0|21.625|
| S2 |0|50|0|0|
| S3 |0|0|0|0|
| Goal|0|0|0|0|

Notice that SARSA only improved after the robot actually chose the good action.

---

# Final Q Table (After Many Episodes)

| State | Up | Down | Left | Right |
|--------|----|------|------|--------|
| S1 |0|12|0|82|
| S2 |0|100|45|0|
| S3 |18|0|0|88|
| Goal|0|0|0|0|

---

# Prediction

Suppose Robot is at

```
S1
```

Q Values

| Action | Q Value |
|----------|---------|
| Up |0|
| Down |12|
| Left |0|
| Right |82|

Prediction

```
Choose Right
```

because

```
82 is Maximum.
```

---

# SARSA Algorithm (Pseudo Code)

```
Initialize Q-table with zeros

For each Episode

    Select Current State

    Choose Action using ε-Greedy

    Repeat

        Perform Action

        Observe Reward

        Observe Next State

        Choose Next Action

        Update

        Q(s,a)=Q(s,a)+α[R+γQ(s',a')−Q(s,a)]

        State = Next State

        Action = Next Action

    Until Goal

Repeat for many Episodes
```

---

# Why is SARSA called On-Policy?

Because

```
Learning Policy

=

Behavior Policy
```

The algorithm learns from the **same action that it actually performs**, not from the best possible action.

---

# Q-Learning vs SARSA

| Q-Learning | SARSA |
|------------|--------|
| Uses Maximum Future Q-value | Uses Actual Next Action Q-value |
| Off-Policy | On-Policy |
| More Aggressive | More Conservative |
| Faster Learning | Safer Learning |
| May take risky shortcuts | Avoids risky actions |

---

# Time Complexity

```
Training

O(Episodes × Steps)

Prediction

O(Number of Actions)
```

---

# Advantages

- Easy to understand
- Safer learning strategy
- Suitable for uncertain environments
- Stable policy updates
- Good for robot navigation

---

# Limitations

- Slower than Q-Learning
- Large Q-table for many states
- Not suitable for high-dimensional state spaces
- Cannot directly process images or continuous inputs

---

# Applications

- Robot Navigation
- Autonomous Delivery Robots
- Traffic Signal Control
- Warehouse Automation
- Path Planning
- Game AI
- Industrial Automation
- Safe Decision-Making Systems

In [64]:
import numpy as np
import gymnasium as gym

In [66]:
env = gym.make("FrozenLake-v1", is_slippery=False)

state_size = env.observation_space.n
action_size = env.action_space.n

print("States:", state_size)
print("Actions:", action_size)

States: 16
Actions: 4


In [68]:
q_table = np.zeros((state_size, action_size))

In [70]:
learning_rate = 0.8
gamma = 0.95

epsilon = 1.0
epsilon_decay = 0.999
epsilon_min = 0.01

episodes = 10000

In [72]:
for episode in range(episodes):

    state, _ = env.reset()

    
    if np.random.rand() < epsilon:
        action = env.action_space.sample()
    else:
        action = np.argmax(q_table[state])

    done = False

    while not done:

        next_state, reward, terminated, truncated, _ = env.step(action)

        done = terminated or truncated

        # Choose next action (ε-greedy)
        if np.random.rand() < epsilon:
            next_action = env.action_space.sample()
        else:
            next_action = np.argmax(q_table[next_state])

       
        q_table[state, action] = q_table[state, action] + learning_rate * (
            reward +
            gamma * q_table[next_state, next_action] -
            q_table[state, action]
        )

        state = next_state
        action = next_action

    if epsilon > epsilon_min:
        epsilon *= epsilon_decay

In [73]:
print(q_table)

[[0.1523259  0.77378094 0.14545777 0.61847987]
 [0.54914103 0.         0.08099395 0.02775749]
 [0.16160559 0.14396876 0.14675213 0.08709583]
 [0.1980739  0.         0.14226912 0.16532334]
 [0.15991912 0.81450625 0.         0.15843372]
 [0.         0.         0.         0.        ]
 [0.         0.76284095 0.         0.11307588]
 [0.         0.         0.         0.        ]
 [0.66820818 0.         0.857375   0.32048634]
 [0.63157388 0.86098456 0.9025     0.        ]
 [0.68152178 0.95       0.         0.7494119 ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.83539203 0.95       0.77010766]
 [0.89868814 0.95       1.         0.84051185]
 [0.         0.         0.         0.        ]]


In [74]:
state, _ = env.reset()

done = False

total_reward = 0

while not done:

    action = np.argmax(q_table[state])

    next_state, reward, terminated, truncated, _ = env.step(action)

    done = terminated or truncated

    total_reward += reward

    state = next_state

print("Reward:", total_reward)

Reward: 1


In [75]:
success = 0

for _ in range(100):

    state, _ = env.reset()
    done = False

    while not done:

        action = np.argmax(q_table[state])

        next_state, reward, terminated, truncated, _ = env.step(action)

        done = terminated or truncated

        state = next_state

        if reward == 1:
            success += 1

print("Success Rate:", success, "/100")

Success Rate: 100 /100
